name: "verify action using sample schema"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  validate-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: openapi-github-action
        uses: ./
        with:
          filepath: './schemas/openapiv3.yml'